[book]
authors = ["Lachlan Deakin"]
language = "en"
src = "src"
title = "The zarrs Book"
description = "This book covers the zarrs Rust crate (and associated tools) for the Zarr storage format for multidimensional arrays and metadata"

[build]
create-missing = false

[rust]
# manifest = "./Cargo.toml"
# edition = "2024"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/zarrs/zarrs_book"
additional-js = []
additional-css = ["theme/custom.css"]
cname = "https://book.zarrs.dev"
# site-url = "/"

[preprocessor]

# [output.linkcheck]
# warning-policy = "warn"
